services:
  pocketbase:
    image: pocketbase:0.30.0
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_public:/pb/pb_public
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

## 나중에 여기에 프론트 들어오고
## network 맞춰서 돌리는 건가 봅니다요.